name: sgfenv
channels:
  - defaults
  - conda-forge
dependencies:
  - blas
  - brotli
  - brotli-bin
  - bzip2
  - ca-certificates
  - contourpy
  - cycler
  - expat
  - fonttools
  - freetype
  - icu
  - intel-openmp
  - jpeg
  - kiwisolver
  - krb5
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libdeflate
  - libffi
  - libpng
  - libpq
  - libtiff
  - libwebp-base
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pillow
  - pip
  - ply
  - pyparsing
  - pyqt
  - pyqt5-sip
  - python
  - python-dateutil
  - qt-main
  - setuptools
  - sip
  - six
  - sqlite
  - tbb
  - tk
  - tornado
  - tzdata
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - annotated-types
      - anyio
      - click
      - colorama
      - fastapi
      - h11
      - httptools
      - idna
      - opencv-python
      - pipdeptree
      - pydantic
      - pydantic-core
      - python-dotenv
      - python-multipart
      - pyyaml
      - scipy
      - sgfmill
      - sniffio
      - starlette
      - typing-extensions
      - uvicorn
      - watchfiles
      - websockets
